# Deploy to WP.org
name: Test Deployment

on:
  push:
    branches: [ test-deploy ]
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "22.x"
      - name: Running NPM Install & Build For Gutenberg
        run: |
          npm ci && npm run build
      - name: Running NPM Install & Build for Admin Panel
        run: |
          cd includes/Admin/Settings && npm ci && npm run prod && cd ../../..
      - name: Optimize the Composer autoloader
        run: composer dump-autoload --no-dev --optimize --no-interaction
