# Deploy to WP.org
name: Test Deployment

on:
  push:
    branches: [ test-deploy ]
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Running NPM Install & Build For Gutenberg
        run: |
          npm ci && npm run build
      - name: Running NPM Install & Build for Admin Panel
        run: |
          cd includes/Admin/Settings && npm ci && npm run prod && cd ../../..